### ISSUE TITLE
bsp目录的Driver 内容怎么理解？

### ISSUE THREAD

**Issue by jwq2011** [Mac-Rsh/mr-library#2]
我看现有的 Driver 的示例是基于 MCU的，如果是用作对基于 linux 的驱动程序进行控制，请教下使用方法

**Comment by Mac-Rsh** [comment]
> 我看现有的 Driver 的示例是基于 MCU的，如果是用作对基于 linux 的驱动程序进行控制，请教下使用方法

其实很不建议在linux上使用这个，linux上有可靠的设备驱动。如果要对接我这个需要把driver替换成对应功能的实现就行了。

**Comment by Mac-Rsh** [comment]
driver主要实现操作硬件所需要接口
